server:
  port: 8080

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbm?autoReconnect=true&useServerPreparedStmts=false&rewriteBatchedStatements=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 120000
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000



# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration.map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml

management:
  health:
    defaults:
      enabled: false
logging:
  level:
    top.trumandu: debug