server:
  port: 8080

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sbm?autoReconnect=true&useServerPreparedStmts=false&rewriteBatchedStatements=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    initial-size: 2
    min-idle: 1
    max-active: 10
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000



# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration.map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml

management:
  health:
    defaults:
      enabled: false
logging:
  level:
    top.trumandu: debug